### ISSUE TITLE
Why Only Support Emacs 25?

### ISSUE THREAD

**Issue by sshaw** [stardiviner/major-mode-icons#2]

**Comment by stardiviner** [comment]
I forgot the reason. Maybe because the difference of `cl` and `cl-lib` ?

**Comment by sshaw** [comment]
You're [using `map`](https://github.com/stardiviner/major-mode-icons/blob/a9b0028828850025e46e1c94d725152969d0fe55/major-mode-icons.el#L26), which is not included in versions < 25. 

Instead of [`map-keys`](https://github.com/stardiviner/major-mode-icons/blob/a9b0028828850025e46e1c94d725152969d0fe55/major-mode-icons.el#L125), you can say `(mapcar 'car  major-mode-icons--major-mode-list)`.

**Comment by stardiviner** [comment]
Updated. Thanks.

**Comment by sshaw** [comment]
Where's the updated version? I couldn't find it.

**Comment by stardiviner** [comment]
@sshaw  Check out here. https://github.com/stardiviner/major-mode-icons/commit/a3ba6c58e8a97193c8de37a2855acc304812ccaa

**Comment by sshaw** [comment]
> Or do you mean update package version in file meta data Version: v0.1?

Yeah, I was looking at the requires line and I still see it's 25

**Comment by stardiviner** [comment]
Oh, I totally forgot that line. sorry, I changed to `24.3`, ready to push. network slow.

**Comment by sshaw** [comment]
Running under 24.4.1 I got this when compiling:
```
Compiling file /var/folders/fn/5bmn_rf52x54hj7lxsw5c7ch0000gn/T/try27385N5Q/major-mode-icons-20170227.2207/major-mode-icons.el at Wed Mar  1 00:59:12 2017
Entering directory `/var/folders/fn/5bmn_rf52x54hj7lxsw5c7ch0000gn/T/try27385N5Q/major-mode-icons-20170227.2207/'
major-mode-icons.el:57:1:Error: Symbol's value as variable is void: major-mode-icons-icons-style
```

**Comment by stardiviner** [comment]
I pushed hotfix already. Thanks for reporting.
